"""Add completed_recommendations

Revision ID: d95dd4322497
Revises: a760f19e2d04
Create Date: 2026-06-12 00:37:28.157239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95dd4322497'
down_revision: Union[str, Sequence[str], None] = 'a760f19e2d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_analyses', sa.Column('completed_recommendations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_analyses', 'completed_recommendations')
    # ### end Alembic commands ###
